apiVersion: v1
kind: Service
metadata:
  name: el-github-listener
spec:
  type: NodePort
  ports:
    - name: http-listener
      port: 8080
      targetPort: 8080
      nodePort: 30080
  selector:
    eventlistener: github-listener